/**
 * Snippet Builder
 *
 * Builds animation snippets from viseme events, matching the format
 * of the reference viseme snippets (e.g., lipsync_hello.json).
 *
 * Key features:
 * - Viseme curves (indices 0-14) with trapezoidal envelope (ramp up → hold → ramp down)
 * - Jaw bone rotation auto-generated by snippetToClip using visemeJawAmounts from preset
 * - snippetCategory: "combined" to support both viseme and AU curves
 *
 * Reference: lipsync_hello.json, lipsync_world.json
 */

import type {
  VisemeEvent,
  VocalSnippet,
  AnimationCurve,
  VocalConfig,
} from './types';
import {
  DEFAULT_VOCAL_CONFIG,
  VOCAL_SNIPPET_CATEGORY,
} from './types';

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

// Ramp time for viseme envelope (seconds)
// Reduced from 0.02 to allow hold time for short phonemes (20-40ms)
const RAMP_SEC = 0.008;

// Peak intensity for viseme morphs (matches reference snippets, 0-1 scale)
const PEAK_INTENSITY = 0.9;
const INTENSITY_EPS = 1e-3;

// ─────────────────────────────────────────────────────────────────────────────
// Curve Building
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a single viseme curve with trapezoidal envelope
 *
 * Shape matches reference snippets (lipsync_hello.json):
 * - Ramp up: 0 → 0.9 over RAMP_SEC
 * - Hold: 0.9 for duration
 * - Ramp down: 0.9 → 0 over RAMP_SEC
 */
function buildVisemeCurve(
  startMs: number,
  durationMs: number
): AnimationCurve {
  const startSec = startMs / 1000;
  const durationSec = durationMs / 1000;

  // Ensure we have room for ramp up and down
  const holdDuration = Math.max(0, durationSec - RAMP_SEC * 2);

  const rampUpEnd = startSec + RAMP_SEC;
  const holdEnd = rampUpEnd + holdDuration;
  const rampDownEnd = holdEnd + RAMP_SEC;

  return [
    { time: startSec, intensity: 0 },
    { time: rampUpEnd, intensity: PEAK_INTENSITY },
    { time: holdEnd, intensity: PEAK_INTENSITY },
    { time: rampDownEnd, intensity: 0 },
  ];
}

/**
 * Remove consecutive keyframes with the same intensity
 */
function deduplicateCurve(curve: AnimationCurve): AnimationCurve {
  if (curve.length <= 1) return curve;

  const result: AnimationCurve = [curve[0]];

  for (let i = 1; i < curve.length; i++) {
    const prev = result[result.length - 1];
    const curr = curve[i];

    // Keep if intensity changed significantly or it's the last keyframe
    if (
      Math.abs(curr.intensity - prev.intensity) > INTENSITY_EPS ||
      i === curve.length - 1
    ) {
      result.push(curr);
    }
  }

  return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// Coarticulation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Apply coarticulation blending between adjacent visemes
 *
 * Coarticulation creates smoother transitions by:
 * 1. Starting the next viseme slightly before the current one ends
 * 2. Blending intensities during the overlap period
 */
function applyCoarticulation(
  curves: Record<string, AnimationCurve>,
  events: VisemeEvent[],
  strength: number
): Record<string, AnimationCurve> {
  if (strength <= 0 || events.length < 2) return curves;

  const blendedCurves = { ...curves };

  for (let i = 0; i < events.length - 1; i++) {
    const current = events[i];
    const next = events[i + 1];

    const currentEnd = current.offsetMs + current.durationMs;
    const nextStart = next.offsetMs;
    const gap = nextStart - currentEnd;

    // Only blend if visemes are close together
    if (gap < 50 && gap > -30) {
      const currentKey = String(current.visemeId);
      const nextKey = String(next.visemeId);

      // Extend current viseme slightly
      if (blendedCurves[currentKey]) {
        const lastIdx = blendedCurves[currentKey].length - 1;
        if (lastIdx >= 0) {
          const extendMs = 10 * strength;
          blendedCurves[currentKey][lastIdx].time += extendMs / 1000;
        }
      }

      // Start next viseme slightly early
      if (blendedCurves[nextKey]) {
        const anticipateMs = 15 * strength;
        blendedCurves[nextKey][0].time = Math.max(
          0,
          blendedCurves[nextKey][0].time - anticipateMs / 1000
        );
      }
    }
  }

  return blendedCurves;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Builder
// ─────────────────────────────────────────────────────────────────────────────

let snippetCounter = 0;

/**
 * Build a vocal animation snippet from viseme events
 */
export function buildVocalSnippet(
  events: VisemeEvent[],
  config?: Partial<VocalConfig>,
  name?: string
): VocalSnippet {
  const cfg: Required<Omit<VocalConfig, 'engine' | 'animationAgency'>> = {
    ...DEFAULT_VOCAL_CONFIG,
    ...config,
  };

  const {
    priority,
    jawScale,
  } = cfg;

  // Generate unique name if not provided
  const snippetName = name ?? `vocal_${Date.now()}_${++snippetCounter}`;

  // Use viseme events exactly as provided.
  const filteredEvents = events;

  if (filteredEvents.length === 0) {
    return {
      name: snippetName,
      snippetCategory: VOCAL_SNIPPET_CATEGORY,
      snippetPriority: priority,
      // Viseme timelines are already scaled before they reach the builder.
      snippetPlaybackRate: 1.0,
      snippetIntensityScale: cfg.intensity,
      snippetJawScale: jawScale,
      loop: false,
      maxTime: 0,
      curves: {},
    };
  }

  // Build curves for each viseme with trapezoidal envelope
  const curves: Record<string, AnimationCurve> = {};

  for (const event of filteredEvents) {
    const key = String(event.visemeId);
    const curve = buildVisemeCurve(event.offsetMs, event.durationMs);

    // Merge curves for same viseme
    if (curves[key]) {
      curves[key] = mergeCurves(curves[key], curve);
    } else {
      curves[key] = curve;
    }
  }

  // Sort each curve by time
  for (const key of Object.keys(curves)) {
    curves[key].sort((a, b) => a.time - b.time);
  }

  // Note: Jaw bone rotation is now auto-generated by snippetToClip when autoVisemeJaw=true (default).
  // The snippetJawScale property is passed through ClipOptions to scale the auto-generated jaw.
  // If you need custom jaw curves, set autoVisemeJaw=false and provide AU 26 curves manually.

  // Calculate max time from filtered events
  const lastEvent = filteredEvents[filteredEvents.length - 1];
  const maxTime = (lastEvent.offsetMs + lastEvent.durationMs) / 1000 + RAMP_SEC;

  return {
    name: snippetName,
    snippetCategory: VOCAL_SNIPPET_CATEGORY,
    snippetPriority: priority,
    // Keep clip playback neutral so we do not double-apply speech rate.
    snippetPlaybackRate: 1.0,
    snippetIntensityScale: cfg.intensity,
    snippetJawScale: jawScale,
    loop: false,
    maxTime,
    curves,
  };
}

/**
 * Merge two curves for the same viseme, handling overlaps
 */
function mergeCurves(
  existing: AnimationCurve,
  incoming: AnimationCurve
): AnimationCurve {
  const merged = [...existing, ...incoming];
  // Sort by time
  merged.sort((a, b) => a.time - b.time);
  return deduplicateCurve(merged);
}

/**
 * Build a snippet for a single word
 */
export function buildWordSnippet(
  word: string,
  visemeEvents: VisemeEvent[],
  config?: Partial<VocalConfig>
): VocalSnippet {
  const name = `vocal_${word.toLowerCase().replace(/[^a-z]/g, '')}_${Date.now()}`;
  return buildVocalSnippet(visemeEvents, config, name);
}

/**
 * Build a snippet for text (phrase or sentence)
 */
export function buildTextSnippet(
  text: string,
  visemeEvents: VisemeEvent[],
  config?: Partial<VocalConfig>
): VocalSnippet {
  // Create a short identifier from the text
  const words = text.split(/\s+/).slice(0, 3).join('_').toLowerCase().replace(/[^a-z_]/g, '');
  const name = `vocal_${words}_${Date.now()}`;
  return buildVocalSnippet(visemeEvents, config, name);
}
